### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by geraldus** [geraldus/iot-project-tracker#1]
+ [x] Создание нового проекта
  + [x] Сервреная часть, Haskell (back-end)
  + [x] Клиентская часть, ReactJS / TS, (front-end)
+ [ ] Авторизация для держателей магазинов
  + [ ] Распределение по ролям: администратор, владелец магазина, покупатель
  + [ ] Регистрация для владельцев магазинов
    + [ ] Страницы входа, регистрации, восстановления / сброса пароля (front-end)
    + [ ] Функционал входа, регистрации, восстановления / сброса пароля (back-end)
  + [ ] Авторизация по ролям
+ [ ] Загрузка изображений на лету
+ [ ] Функционал создания магазина
  + [ ] Страница создания магазина (front-end)
    + [ ] Название, логотип, описание
  + [ ] Функционал создания магазина (back-end)
  + [ ] Страница редактирования магазина (front-end)
  + [ ] Функционал редактирования магазина (back-end)
+ [ ] Функционал создания товара
+ [ ] Гибкая настройка товаров (вариации параметров: цвет, тип, пр.)
+ [ ] Страница просмотра магазина и каталога товаров для покупателей
+ [ ] Система фильтрации товаров (поиск и выборка) для покупателей
+ [ ] Инструменты для таргетированной рекламы (посадочные страницы - услуга)
+ [ ] Инструменты для таргетированной рекламы (конструктор с шаблонами)
+ [ ] Работа с доменами (домены третьего уровня, привязка произвольного домена к магазину)
+ [ ] Инструменты SEO
+ [ ] Интеграция платёжных систем (Яндекс.Касса) 
+ [ ] Личный кабинет пользователя (Покупателя)
+ [ ] Аналитика для магазинов (статистика по продажам)
+ [ ] Аналитика посещаемости
+ [ ] Склад
+ [ ] Настраиваемый дизайн магазинов (услуга)
+ [ ] Настраиваемые шаблоны внешнего вида
+ [ ] Двухфакторная аутентификация
